version: '3.4'

services:
  proxy:
    image: nginx:stable
    links:
      - app
    ports:
      - "8089:8080"
    volumes:
      - ./env/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template:ro
      - ./public:/usr/share/nginx/www/public
    environment:
      - NGINX_HOST=test.local
      - NGINX_PORT=8080
      - PHP_FPM_HOST=app
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$PHP_FPM_HOST' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  app:
    build:
      context: ./env
      target: base
    expose:
      - "9000" # PHP-FPM
    volumes:
      - .:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
